language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kign/docker-react-exercise -f Dockerfile.dev .


script:
  - docker run -e CI=true kign/docker-react-exercise npm run test -- --coverage
